<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3085f943cf923dbda2bd200e8f00f0ab
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WebSocket\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WebSocket\\' => 
        array (
            0 => __DIR__ . '/..' . '/textalk/websocket/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3085f943cf923dbda2bd200e8f00f0ab::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3085f943cf923dbda2bd200e8f00f0ab::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
